name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12

      - run: npm ci
      - run: npm run build

      - name: Install github/hub
        run: |
          export HUB_VERSION="2.14.2"
          curl -fsSL https://github.com/github/hub/raw/8d91904208171b013f9a9d1175f4ab39068db047/script/get | bash -s "${HUB_VERSION}"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          RELEASE_NAME="$(jq -r '.name' ./package.json)"
          echo "${RELEASE_NAME} ${TAG_NAME}" > ./release_notes.md
          cd ./build
          ../bin/hub release create \
            --draft \
            --file ../release_notes.md \
            $(for i in $(echo *); do echo -n "--attach ${i}#${i} "; done) \
            "${TAG_NAME}"
